language: ruby
rvm:
- 2.5.3
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure:
    OPEN_WEATHER_API: 8b0455632c870ed1f0fa5da14ffccfe6
    GEOCODING_API_KEY: AIzaSyBIPdFTCwhCGhTYgMOsm8R6JVJqMqeeV0U
    UNSPLASH_ACCESS_KEY: qPXPO-mtsHKAQwclHBQv_aQ6abE3u3uwSk9W_0KSvEs
    UNSPLASH_SECRET_KEY: Ug1LemyqHz9zv0ESTFO0CB6RcTOd6ded1Jl_Ew42B48
  app: kd-sweater-weaher
  run: rails db:{migrate,seed}
  on:
    repo: kelshadarby/sweater_weather
  skip_cleanup: 'true'
